# Generated by Django 5.0.2 on 2024-03-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi_padi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=50)),
                ('kode_provinsi', models.IntegerField()),
                ('bulan_tahun', models.DateField()),
                ('luas_panen', models.FloatField()),
                ('produktivitas', models.FloatField()),
                ('curah_hujan', models.FloatField()),
                ('hari_hujan', models.IntegerField()),
                ('produksi', models.FloatField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='training',
            new_name='training_testing',
        ),
        migrations.DeleteModel(
            name='testing',
        ),
    ]
