# Generated by Django 5.0.2 on 2024-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi_padi', '0002_predict_rename_training_training_testing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='produksi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
